spring:
  application:
    name: ms-sale
  datasource:
    url: ${db.url}
    username: ${db.usr}
    password: ${db.pwd}
  jpa:
    hibernate:
      ddl-auto: create-drop
  profiles:
    default: default
  config:
    import: "optional:configserver:http://localhost:7777"
  data:
    web:
      pageable:
        page-parameter: p
        size-parameter: limit
        
server:
  servlet:
    context-path: /api/sale
  port: 0

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/